### ISSUE TITLE
Create creative README.md

### ISSUE THREAD

**Issue by iamdipanshusingh** [101Loop/InstagramClone-BE#12]

**Comment by this-is-shashank-mishra** [comment]
Hey @iamdipanshusingh, provide me some description and i can work on this!

**Comment by stephin007** [comment]
hey @this-is-shashank-mishra , Thankyou for showing interest in the project.
Its an instagram clone intended to have many features, but currently it has only the signin, signup and Create post.
In future, i am hoping to add many other models and routes for other features like comment, like, follow other user. etc

**Comment by afred-khan** [comment]
so @stephin007 you want the readme files including the future perspectives as well? like should I include all the likes, and posts screenshots and all?

**Comment by stephin007** [comment]
@this-is-shashank-mishra or anyone else reding this, after you have done with the changes, please add me as the reviewer

**Comment by stephin007** [comment]
Yes, @afred-khan  you can assume any feature that, you can assume for original instagram, would be there for this clone project
